// lib/countries.ts
export const chaturbateCountries: Record<string, string> = {
  AT: "Austria",
  AU: "Australia",
  BE: "Belgium",
  CA: "Canada",
  CH: "Switzerland",
  DE: "Germany",
  DK: "Denmark",
  FI: "Finland",
  FK: "Falkland Islands (Malvinas)",
  FO: "Faroe Islands",
  FR: "France",
  GB: "United Kingdom",
  GG: "Guernsey",
  GI: "Gibraltar",
  GL: "Greenland",
  IE: "Ireland",
  IS: "Iceland",
  JE: "Jersey",
  JP: "Japan",
  LI: "Liechtenstein",
  LU: "Luxembourg",
  NL: "Netherlands",
  NO: "Norway",
  NZ: "New Zealand",
  QA: "Qatar",
  SE: "Sweden",
  SG: "Singapore",
  SM: "San Marino",
  UM: "United States Minor Outlying Islands",
  US: "United States",
  VI: "United States Virgin Islands",
  AE: "United Arab Emirates",
  AW: "Aruba",
  BN: "Brunei Darussalam",
  BR: "Brazil",
  BS: "The Bahamas",
  CY: "Cyprus",
  ES: "Spain",
  GQ: "Equatorial Guinea",
  GR: "Greece",
  HK: "Hong Kong",
  IL: "Israel",
  IM: "Isle of Man",
  IT: "Italy",
  KR: "South Korea",
  KW: "Kuwait",
  KY: "Cayman Islands",
  MO: "Macau",
  PF: "French Polynesia",
  PR: "Puerto Rico",
  PT: "Portugal",
  SI: "Slovenia",
  VG: "British Virgin Islands",
  AG: "Antigua and Barbuda",
  AI: "Anguilla",
  BB: "Barbados",
  BH: "Bahrain",
  CK: "Cook Islands",
  CL: "Chile",
  CZ: "Czech Republic",
  EE: "Estonia",
  GU: "Guam",
  HR: "Croatia",
  HU: "Hungary",
  IN: "India",
  KN: "Saint Kitts and Nevis",
  LB: "Lebanon",
  LT: "Lithuania",
  LV: "Latvia",
  MP: "Northern Mariana Islands",
  MT: "Malta",
  MX: "Mexico",
  NC: "New Caledonia",
  OM: "Oman",
  PL: "Poland",
  RU: "Russia",
  SA: "Saudi Arabia",
  SC: "Seychelles",
  SK: "Slovakia",
  TR: "Turkey",
  TT: "Trinidad and Tobago",
  TW: "Taiwan",
  UY: "Uruguay",
  VE: "Venezuela",
  CO: "Colombia",
  MN: "Mongolia",
  MU: "Mauritius",
  PH: "Philippines",
  RO: "Romania",
  TH: "Thailand",
  UA: "Ukraine",
  AR: "Argentina",
  KE: "Kenya",
};
